name: Deploy to Heroku

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Generate env from secrets
              run: |
                  echo "${{ secrets.TERBANGIN_HEROKU_ENV }}" | tr ';' '\n' >> .env
                  cat .env

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            - name: Deploy to Heroku
              uses: akhileshns/heroku-deploy@v3.13.15 # or the latest version
              with:
                  heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
                  heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
                  heroku_email: ${{ secrets.HEROKU_EMAIL }}

            - name: Set Heroku Config Vars
              run: |
                  heroku config:set $(cat .env | xargs) -a ${{ secrets.HEROKU_APP_NAME }}
